# Generated by Django 4.1rc1 on 2022-07-29 09:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boat",
            name="captain_photo",
            field=models.ImageField(
                upload_to=core.models.Boat.rename_captain_boat_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="deckhand_photo",
            field=models.ImageField(
                upload_to=core.models.Boat.rename_deckhand_boat_photo_path
            ),
        ),
    ]
