# Generated by Django 4.1rc1 on 2022-07-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="Boat",
            new_name="boat",
        ),
    ]
