# Generated by Django 4.1rc1 on 2022-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_boat_captain_photo_alter_boat_deckhand_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="association",
            field=models.CharField(
                choices=[
                    (
                        "atbo",
                        "Association of Tourists Boat Operators and Water Transporters of Nigeria",
                    ),
                    ("ufta", "United Ferry Transporters' Association"),
                    ("iboa", "integrated Boat Operators Association"),
                ],
                default="atbo",
                max_length=4,
            ),
        ),
    ]
