# Generated by Django 4.1rc1 on 2022-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_operator_association"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boat",
            old_name="captain_certificaiton",
            new_name="captain_certification",
        ),
        migrations.AlterField(
            model_name="operator",
            name="association",
            field=models.CharField(
                choices=[
                    (
                        "atbo",
                        "Association of Tourists Boat Operators and Water Transporters of Nigeria",
                    ),
                    ("ufta", "United Ferry Transporters' Association"),
                    ("iboa", "Integrated Boat Operators Association"),
                ],
                default="atbo",
                max_length=4,
            ),
        ),
    ]
