# Generated by Django 4.1rc1 on 2022-07-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0004_rename_captain_certificaiton_boat_captain_certification_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterUniqueTogether(
            name="boat",
            unique_together={("name", "operator")},
        ),
    ]
