# Generated by Django 4.1rc1 on 2022-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_boat_options_alter_operator_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boat",
            name="captain_photo",
            field=models.ImageField(upload_to="mediafiles/captains/"),
        ),
    ]
